### PR TITLE
UCLALIB-233: custom panes for improved icon integration on opening hours

### PR DESCRIPTION
**Pull request by emb03**
@jameswilson adds custom panes for telephone and email icons for uclalib_opening_hours

### CODE REVIEW

**Comment by jameswilson** [comment]
@emb03 The comment above seems to be wrong.   Also, Shouldnt this be replacing the existing field panes on the opening hours panel?

**Comment by emb03** [comment]
@jameswilson I guess I forgot to edit my comment, I updated it to reflect the PR.

**Comment by emb03** [comment]
@jameswilson yes, it should be replacing the existing panes, but Features did not reflect any changes for Page Manager.

**Comment by emb03** [comment]
@jameswilson here is the URL(s) (where 392 is just one of the nodes I changed) I added the new panes:
/node/392/panelizer/hours_page/content
Here is a screencap of what I exported for this PR:
http://awesomescreenshot.com/0d364cquc0 (will disappear in 3 days)

**Comment by jameswilson** [comment]
`/node/392/panelizer/hours_page/content` is the overridden panelizer for node/392.  You need to find and edit the default panelizer configuration for the "hours_page" view mode of the Location content type.

**Pull request closed without merging**
